spring:
  application:
    name: task-me-please

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/task_me_please}
    username: ${SPRING_DATASOURCE_USERNAME:postgres_user}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres_password}

  output:
    ansi:
      enabled: always

server:
  port: ${PORT:8181}

logging:
  level:
    root: INFO

gg:
  jte:
    development-mode: ${JTE_DEVELOPMENT_MODE:true}