spring:
  application:
    name: task-me-please

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/task_me_please}
    username: ${SPRING_DATASOURCE_USERNAME:postgres_user}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres_password}

  output:
    ansi:
      enabled: always

app:
  base-url: ${APP_BASE_URL:http://localhost:8181}
  brevo:
    api-key: ${BREVO_API_KEY:}
    api-url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
    connect-timeout: ${BREVO_CONNECT_TIMEOUT:5s}
    read-timeout: ${BREVO_READ_TIMEOUT:5s}
  mail:
    from: ${MAIL_FROM:no-reply@taskmeplease.online}
  security:
    remember-me-key: ${REMEMBER_ME_KEY}

server:
  port: ${PORT:8181}

logging:
  level:
    root: INFO

gg:
  jte:
    development-mode: ${JTE_DEVELOPMENT_MODE:true}
